name: "Go sum fix"
description: "Update .terraform.lock.hcl."
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
  git_user:
    description: "User name of commit author."
    required: true
  git_email:
    description: "E-mail address of commit author."
    required: true
  commit_style:
    description: "Commit style. (add|squash)"
  commit_message:
    description: "Commit message."
  push:
    description: "Push to the branch? (no|yes|force)"
  lock_file_paths:
    description: "Space separated list of the paths to the directories of .terraform.lock.hcl. Automatically detected by default."
  platforms:
    description: "Space separated list of the platforms. Windows, 64-bit Linux and macOS are default."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "refresh-ccw"
  color: "white"
